title: Quan M. Tran
tagline: Infectious disease modeler
description: >-
  Quan M. Tran, MD, PhD, models mosquito-borne disease transmission to inform
  vaccination policy, outbreak response, and disease burden estimation.

url: "https://tranquanc123.github.io"
baseurl: "/tranminhquan.io"
repository: tranquanc123/tranminhquan.io

author:
  name: Quan M. Tran
  email: tranminhquan12332192@gmail.com

profile_image: /assets/img/headshot-960.jpg
image: /assets/img/og-profile-optimized.jpg
logo: /assets/img/logo.png

social:
  name: Quan M. Tran
  links:
    - https://scholar.google.com/citations?user=koL60SsAAAAJ&hl=en
    - https://www.linkedin.com/in/quan-tran-minh-148a43116/
    - https://github.com/tranquanc123

theme: jekyll-theme-minimal

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
permalink: pretty
lang: en
timezone: Asia/Ho_Chi_Minh

exclude:
  - vendor/
  - docs/
  - script/
  - jekyll-theme-minimal.gemspec
  - README.md
  - thumbnail.png
