title: Quan M. Tran
tagline: Infectious disease modeler
description: >-
  Infectious disease modeler working on arboviral dynamics, vaccine impact, 
  Bayesian methods, and outbreak analytics.

url: "https://tranquanc123.github.io"
baseurl: "/tranminhquan.io"
repository: tranquanc123/tranminhquan.io

author:
  name: Quan M. Tran
  email: tranminhquan12332192@gmail.com

image: /assets/img/headshot.jpg

theme: jekyll-theme-minimal

plugins:
  - jekyll-seo-tag

markdown: kramdown
permalink: pretty
lang: en
timezone: Asia/Ho_Chi_Minh

exclude:
  - docs/
  - script/
  - jekyll-theme-minimal.gemspec
  - README.md
  - thumbnail.png
